name: Publish

on:
  push:
    branches: master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - run: yarn install

      - name: Publish 📄
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
